import React from 'react'
import type { Metadata } from 'next'
import localFont from 'next/font/local'
import { ToastContainer } from 'react-toastify'
import styles from './page.module.css'

import './globals.css'
import 'react-toastify/dist/ReactToastify.css'
import { cn } from '@/lib/utils/cn'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body
        className={cn(geistSans.variable, geistMono.variable, styles.container)}
      >
        {children}

        <ToastContainer autoClose={5000} closeOnClick />
      </body>
    </html>
  )
}
